### ISSUE TITLE
s3 support

### ISSUE THREAD

**Issue by HenryGeorgist** [water-tech-repos/wat-hydrograph-stats-py#18]
our primary storeage capabilities right now are s3 and local file storage. we arent yet mature enough to handle azure.

**Comment by thwllms** [comment]
@HenryGeorgist understood, makes sense to keep focused on that at this stage. The Azure Blob Storage test code is here because we talked about Azure support as a possibility a while ago and the [fsspec library](https://filesystem-spec.readthedocs.io/en/latest/) makes it really easy to abstract away remote storage like S3, Azure Blob, etc. And I had used the `azurite` Docker image before to mock Azure Blob Storage locally.

Are there specific updates that we need to make for this issue?

**Comment by HenryGeorgist** [comment]
no, just making sure you know we arent supporting azure yet. wasnt sure if i had communicated that.

**Comment by thwllms** [comment]
Gotcha; Seth mentioned that when he and I chatted the other day.
